force-billing/main/default/objects/Order/fields/NumberOfLines__c.field-meta.xml
<CustomField>
    <fullName>NumberOfLines__c</fullName>
    <label>Number of Lines</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-billing/main/default/classes/selectors/OrdersSelector.cls
public inherited sharing class OrdersSelector {

    public List<Order> selectById(Set<Id> orderIds) {
        return [select Id, NumberOfLines__c from Order where Id in :orderIds];
    }

    public List<Order> selectThisWeeksOrders() {
        return [select Id from Order 
                where EffectiveDate = THIS_WEEK and Invoiced__c != true
                order by Name];
    }

    public Map<Id, Integer> selectLineCountById(Set<Id> orderIds) {
        Map<Id, Integer> lineCountByOrderId = new Map<Id, Integer>();
        for(Order order : selectById(orderIds)) {
            lineCountByOrderId.put(order.Id, Integer.valueOf(order.NumberOfLines__c));
        }
        return lineCountByOrderId;
    }
}